### ISSUE TITLE
Table Recognition Failure (Grafana v6.4.0)

### ISSUE THREAD

**Issue by reidko** [michaeldmoore/michaeldmoore-multistat-panel#28]
When querying data from an Influx data source and changing the format from "Time Series" to "Table", I get a "Non-Table type data received" error with a Grafana instance running v6.4.0. I had the instance downgraded to v6.3.5 and it works fine. The screenshot below shows the data in table format (when I change the visualization from multistat to table).

![error](https://user-images.githubusercontent.com/56081179/66052849-49f38400-e4ff-11e9-92e7-19255148b761.PNG)
![table](https://user-images.githubusercontent.com/56081179/66052859-4cee7480-e4ff-11e9-83fe-71081d057aa9.PNG)

**Comment by michaeldmoore** [comment]
Yes,. I just got s heads-up from Grafana corp saying you had found an
issue.  I'm looking at it right now, and it seems something in the JSON
data response structure changed from 6.3.0 to 6.4.x and this panel is, as
you noticed, currently broken

The fix should be pretty straightforward, so look out for an email later
today or at worst tomorrow with the fix.

Michael

**Comment by michaeldmoore** [comment]
OK, I got a fix in place and submitted it to the grafana plugin repo.

Grafana 6.4.0 update introduced a bug which removed the type='table' value for non-timeseries data queries. Multistat, which only works with table-formatted data relied on this property. This minor version release adds an alternative method of determining the query type (namely the existence of a columns property which only table-formatted queries produce

The fix was very simple and I don't anticipate it introducing any side effects.

Fingers crossed, Grafana will be able to test and approve this change quickly

**Comment by michaeldmoore** [comment]
FYI - the underlying problem introduced in Grafana 6.4.0 has been fixed with the newly released version 6.4.2
