### ISSUE TITLE
Column based Highlighting / Flashing

### ISSUE THREAD

**Issue by devopsadmn2018** [michaeldmoore/michaeldmoore-multistat-panel#39]
hello Michael;

First of all Thanks for developing this plugin... there is lots of potential uses of same...

I would love to see a feature upgrade as explained below... Possibly could be a higly beneficial feature at lower efforts...

Feature: Extend current High/Low-Limit-based-bar-highlighting/flashing to Column based highlighting with limiting value.

possible change could be:
1. Column Definition: one more field to take non-mandatory input as Highlight column.
2.  on selecting column from that dropdown. it should allow  "Lines and Limits >> High / Low limit"  fields to appear to enable limit selections based on values from selected column.
3. appropriate code changes to  accommodate above change based on values from selected column's newly added data at runtime...
for example: say if at runtime a new datarow is added in backend table, which will get fetch by query. If this value is more/less than thresholds defined above then next bar should get highlighted/flashed like it is working for hardcoded limits now...

Regards,
AJ

**Comment by devopsadmn2018** [comment]
so essentially, in current setup; plugin validating data from query against threshold limits defined in High/Low limit and based on same all rows/bars are flashed... but feature request is to validate thresholds against the data from tables another column.
for example: for a given rows of data if say chart is displayed like something below

![image](https://user-images.githubusercontent.com/44631730/79432215-dc2c2700-800e-11ea-8f56-0dffde3af46a.png)

now, having other column in query which finds the BIG-CHANGEs in data, ex. green colored column with values 14.8 & 34.9 then I wanted to flash 34.9's bar.

**Comment by michaeldmoore** [comment]
At first, this sounded very complicated.  But maybe there is a simpler way
of achieving the same result.


At the moment, each bar is colored, and flashes etc., according to the
bar's value in comparison with the upper and lower warning and limit
thresholds.
Internally, there are 5 regions
-2   LowerLimit    Below lower limit
-1   LowerWarning  Below lower warning level
 0   OK            In the normal, or 'OK' range
 1   UpperWarning  Above the upper warning level
 2   UpperLimit    Above the upper limit


How about if your data set included a column to indicate the region -
either by number or region name
Maybe I could define an optional column to define the region - overriding
the region implied by the thresholds and the actual value of each bar.

The only messy thing would be that the settings for bar color and flash
settings etc. are only displayed in the configuration window if the
thresholds are actually set - and then the axis max and min are adjusted to
always include these values.  This could be confusing.

I'm open to this though - if you can create a data set with a
column indicating the display region as above (the column could be any
name) - I could make this work

**Comment by michaeldmoore** [comment]
Then, if the display region column was empty or unrecognizable - the
display attributes would revert to the automatic value/threshold method for
that bar.

Make sense?

**Comment by devopsadmn2018** [comment]
yes Michalel and really thanks for quick reply...
I can get the column data such that it can be (-2,-1,0,1,2) mapped with display region...
I am not sure whether current plugin version has flash functionality based on above region though... if it is please let me know how to configure same...  

**point to note is:** my 'Group col', 'Value col', 'Sort col', 'Datetime col' columns are different than this region column... so i wonder there should be separate section in 'Column Definition' where this configuration required to be set...

thanks a ton again...:-)

**Comment by michaeldmoore** [comment]
I'll need to make some code changes to make this work - and this will take
some days to get working properly.

Let me look into this before making a commitment.

in the mean time, if you can create a CSV file, or excel spreadsheet with a
sample of the data you want to display - that would be helpful.
Michael

**Comment by devopsadmn2018** [comment]
thanks Michael... 
please find the sample data file... 
column configuration can be done as column-headers + added one more column Named 'Region'

[Samplecsvdata.xlsx](https://github.com/michaeldmoore/michaeldmoore-multistat-panel/files/4496581/Samplecsvdata.xlsx)

regards,
AJ

**Comment by michaeldmoore** [comment]
I'm making progress - here's a quick preview using your data file

[image: image.png]

Most of the work has been in getting the configuration screen to work the
way I want.
[image: image.png]

Rather than my first thought - a column with numbers -2,-1,0,1 and 2, I've
made this an expandable set of rule patterns, matching whatever is in the
Recolor column, with various types of matching logic ('Exact' being the
simplest, also List, Subset and reg-ex for full flexibility).  Each rule
controls a color setting for the matched bars.  Any bars not matching any
of the rules will use the default value/threshold bar coloring logic, so
this is backwards compatible with any applications that don't define
recolor rules.

The last bit I need to get working is the optional flash attribute - I can
already define the secondary color and the interval (speed) for each
flashing cycle.  Now I need to make it work.

Michael

**Comment by michaeldmoore** [comment]
I did the release (v1.3.0), which might take a week or so before getting through the Grafana plugin release approval scheme.

I think it solves most, if not all, of the things you were looking for.  Take a look and feel free to reopen this issue if you see a problem.  The updated README explains how it all works.

I had to give up on the flash override though - too many changes would be needed to get this working, and yours is the only request to make this overridable (if I understood you request properly).

**Comment by devopsadmn2018** [comment]
Thanks Michael... :-)
you are awesome...
It would be great if you can add flash functionality as per your convenience... though not hard-&-fast, I think current 1.3.0 would work for me... have to make few tweaks...:-)
 Will let you know in case uncovered any observations...

**Comment by michaeldmoore** [comment]
In a way, flashing IS supported with the 1.3.0 release - (available now on
github directly or in a week or so through the Grafana repository).

Let me try to explain.

Without the recolor rules, bars are colored according to the settings on
the thresholds configuration section.  That is one color for values above
the baseline, one for values below the baseline.  Plus optional alternative
colors for values above or below the upper and lower threshold settings.
If flashing is enabled, these limit colors cycle to secondary colors.  All
very simple.

With recolor rules, the regular (non-flashing) colors of matched bars are
changed, according to the recolor rule setting.  Still simple.

If a bar exceeds a threshold though, AND if the threshold is set to flash -
then the pair of color defined in the flash setting will override the
recolor rule color.  This is not so simple to explain, but that's the way
it worked out.  Originally, I thought I could define an optional flashing
color and period for each recolor rule, but it turned out to be a big
change in the way everything worked.  Also, it isn't at all clear how
anyone would interpret a dashboard with seemingly random flashing color
combinations.

I think for most people who want to color bars using the recolor rules,
they won't also need to use thresholds and/or flashing.  If they do want
the ability to flash bars with out-of-range values, they can do so, knowing
just that the pair of colors involved in the flash cycle won't be affected
by the color of the bar from any recolor rules.  I hope this makes sense.

**Comment by devopsadmn2018** [comment]
great... :-)
>>If a bar exceeds a threshold though, AND if the threshold is set to flash - then the pair of color defined in the flash setting will override the recolor rule color. 
Correct...

>>I think for most people who want to color bars using the recolor rules, they won't also need to use thresholds and/or flashing. 
Correct here too... while using Recolor Rule now, I am not using Thresholds and as said earlier it suffice for my purpose ... :-)

Thanks again Michael... it will be very helpful interaction and definitely this upgrade will help many... Follow Social Distancing... Stay Safe... bye...
