### ISSUE TITLE
grafana cli install support

### ISSUE THREAD

**Issue by pracplayopen** [michaeldmoore/michaeldmoore-multistat-panel#4]
perhaps not the goal, but you'd probably have more uses if you either included an install step in readme or supported cli, eg:

```
grafana-cli plugins install multistat-panel
```

feel free to close if this is intention.  thx for interesting work

**Comment by michaeldmoore** [comment]
Agreed - this part is added automatically when a panel is adopted in the official Grafana plugins directory.  I ran into some formatting and performance issues that got in the way of having it adopted officially - and due to time pressures and the fact that it worked perfectly for the client I created t for - I've left it in this unfinished state for most of the year.

I'm back on the trail though and just about finished with the changes needed to get final approval.  So - fingers crossed - you should see a new/improved version of this including the cli-installer and instructions very soon now.

Most of the changes are cosmetic, but some affect some serious performance issues that could come up with large data sets etc - something I didn't run into myself but others did.  And now, it's all fixed.

**Comment by michaeldmoore** [comment]
I have an updated version of this ready to go - checked in to the 'verticalgroups' branch - soon to be merged (I hope) with the master branch - I'm just waiting for approval from the Grafana code review which is taking forever.


Once the review is over, and incorporated into the grafana plugin repository - the cli support should be automatic
