### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by Breee** [michaeldmoore/michaeldmoore-multistat-panel#44]
I just tried to use your panel .  
The query I used (kube_pod_container_resource_requests_cpu_cores)  returns around 40 rows with 11 columns. 

My browser just freezes and it takes a huge amount of time until everything is useable again. (5 minutes) 

Can you confirm the same performance issues, or is it just us? ;)

**Comment by michaeldmoore** [comment]
I assume you are using more or less up-to-date version of Grafana and
multistat - something certainly doesn't sound right.
Does this only happen with multistat?  Switch over to use the table panel
built into grafana - is that slow too?
If the table panel works OK, try multistat again and see if this is
reproducible.

You might try with a different browser too - just in case.  I've been using
Chrome, but any modern browser *should *work.

Also - if you have the patience - set the aggregation value (in the columns
settings) to 'Last'

If you are still having problems, go to the query inspector and display the
data returned by the query.  In the JSON view, click the 'copy to
clipboard' and paste the results into an email so I can see it here
(assuming there is nothing too confidential, that is)

Multistat can get bogged down with very large data sets - thousands of rows
and columns.  With only 40x11 values, it should be a breeze.
Michael Moore

**Comment by michaeldmoore** [comment]
Any update?  Are you still having this issue or did it just magically 'go away'?

**Comment by Breee** [comment]
hey there, in my case it helped to use instant queries, I recognized that the table was really really big without

**Comment by michaeldmoore** [comment]
So are we OK now?

I've thought about adding a warning when very large data sets are received - maybe a configurable setting to set the maximum number of rows before displaying the warning message.  Just something to think about.

Multistat can get confused, and potentially quite slow when receiving a record set with multiple records for a given label - say with an updating datetime field.  Originally, I always displayed every row as a bar, though superimposed over the same position, based on the uniquness of the label.  To cure this, I added an aggregation option, defaulting to 'last' so that when (in the default case) multiple records exist for a given label, only the last datatime record is used - all the others are discared in the panel itself.  Of course, this is more efficient if the query does the filtering first, but it helped to have this as the default action of the panel.
Aggregation has a number of alternative options, including min, max and mean etc., which mash up all the values for a given label and present a single bar - this does have some odd side effects concerning tooltips etc., but it does serve some users needs.
