### ISSUE TITLE
Column Sorting does not work as expected

### ISSUE THREAD

**Issue by Breee** [michaeldmoore/michaeldmoore-multistat-panel#45]
When sorting columns, there is an issue when using the following type of sort-columns:

Input: 
vl-k8ssvc2-c-02
vl-k8ssvc2-c-01
vl-k8ssvc2-c-03

Output: 
vl-k8ssvc2-c-02
vl-k8ssvc2-c-01
vl-k8ssvc2-c-03

Expected:
vl-k8ssvc2-c-01
vl-k8ssvc2-c-02
vl-k8ssvc2-c-03

**Comment by michaeldmoore** [comment]
Good catch - I recently fixed a problem with sorting by values - so 1.1
sorted after 0.9 etc. - I think this fix must have broken the alphabetical
sorting.  Damn.

Sorry about that.  I'm about to release a new version anyway with a number
of new enhancements, including some cosmetic changes to the configuration
screens, due to the new UI layout in the upcoming Grafana 7.  So this is
perfect timing - I can squeeze in the fix at the same time.  until then,
I'm afraid - alphanumeric sorting is broken :(

Thanks for the report.
Michael Moore

**Comment by michaeldmoore** [comment]
OK, this now works.  For the moment, I haven't released this to the Grafana plugin repo - I still need to do more testing and add something to the documentation.  You can clone this repo into you plugin directory and run this for the time being.

Thanks for the bug tip and look out for an official version update sometime in the next week or two.
