### ISSUE TITLE
Panel plugin not found: michaeldmoore-multistat-panel

### ISSUE THREAD

**Issue by bbruhn91** [michaeldmoore/michaeldmoore-multistat-panel#55]
Using grafanaversion 6.1.0, the plugin does not work. I can select the Multistat panel under visualisation:

![image](https://user-images.githubusercontent.com/43037659/90619454-91672980-e211-11ea-9b1c-3ea1970a5e62.png)

However, if I aim to create the panel, it spits out this error:

`Panel plugin not found: michaeldmoore-multistat-panel`

![image](https://user-images.githubusercontent.com/43037659/90619554-ad6acb00-e211-11ea-9ea2-00720739ac6c.png)

**Comment by michaeldmoore** [comment]
What version of Multistat are you using?  And while you're at it, what is
your environment (OS etc.)?

I had to make some significant changes to support Grafana 7.x.x due to a
change in their API - as far as I know, these changes should have been
backwards-compatible and when testing, it seemed OK with Grafana 6.5.0, but
it is possible something I added before the release has broken this for
some old versions of Grafana..

The best thing (for me, at least) would be to upgrade your installation to
the current version of Grafana.  If this is not possible, see if you can
get an earlier version of Multistat from the github archive.  If you can't
do either of these, let me know and I'll see if there is a simple work
around for your situation.  Shouldn't be too hard.
Michael Moore

**Comment by bbruhn91** [comment]
Updating grafana to the latest version did resolve the issue. Thx!
