### ISSUE TITLE
Influxdb,Date_Time display issue ,in comparison with  Graph

### ISSUE THREAD

**Issue by minitomi** [michaeldmoore/michaeldmoore-multistat-panel#59]
I use influxdb 1.77 , almost same query ,and get same values .see the pictures 
I can not figure out how the x-axle display  really date that can be recognized .
![issue1](https://user-images.githubusercontent.com/74391954/99025803-a94a1180-25a4-11eb-8875-e52f8a6f00d4.png)
![issue2](https://user-images.githubusercontent.com/74391954/99025804-a94a1180-25a4-11eb-8783-3462b9fb9822.png)

**Comment by michaeldmoore** [comment]
Multistat just displays the labels as returned by the query.  Using influx,
it seems the default is to return these as UNIX timestamps (aka seconds
since Bill Gate's birthday :) )

A quick search on Google turns up the time() function that converts these
big integer values (timestamps) to readable strings.

https://docs.influxdata.com/influxdb/v2.0/query-data/flux/manipulate-timestamps/

I don't know much about influxdb though, so I can't tell whether this
function can be incorporated into the query or not, nor (assuming it CAN),
whether you can select a different format, such as one without the seconds
etc.

The secret is to get the query to format the label the way you want it to
appear.  The rest should be easy.
Good luck

Alternatively, Grafana now has the interesting-looking transform feature
that from my brief reading, looks as though it should be able to do the
conversion too.  Maybe use it to create a new field, a formatted date field
from the unix timestamp.

Let me know if you can make either of these work
Michael Moore

**Comment by jerommeke-bos** [comment]
Dear Michael,

Unfortunately, the functions you mentioned don't work for table queries, so I hope you can add a function for the:

- grouping section
- columns section

like the one you'll have for tooltips "Date Format" where it is working.

Best regards,

Jeroen Bos
